/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CtrlCategoria;
import Controlador.CtrlCita;
import Controlador.CtrlCita2;
import Controlador.CtrlCliente;
import Controlador.CtrlCliente2;
import Controlador.CtrlPaciente;
import Controlador.CtrlServicio;
import Controlador.CtrlVeterinario;
import Modulo.Categoria;
import Modulo.Cita;
import Modulo.Cliente;
import Modulo.ConsultaCategoria;
import Modulo.ConsultaCita;
import Modulo.ConsultaCliente;
import Modulo.ConsultaPaciente;
import Modulo.ConsultaServicio;
import Modulo.ConsultaVeterinario;
import Modulo.DireccionVeterinario;
import Modulo.HistoricoPaciente;
import Modulo.Paciente;
import Modulo.Servicio;
import Modulo.Veterinario;

/**
 *
 * @author julian
 */
public class menuGestiones extends javax.swing.JFrame {

    /**
     * Creates new form menuGestiones
     */
    public menuGestiones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        popupMenu1 = new java.awt.PopupMenu();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        mnuAdmin = new javax.swing.JMenuItem();
        mnuVete = new javax.swing.JMenuItem();
        mnuClint = new javax.swing.JMenuItem();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Gestion Veterinario");

        jLabel3.setText("MaskoTika");

        jMenu1.setText(":)");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Módulos");

        mnuAdmin.setText("Módulo de Administración");
        mnuAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAdminActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAdmin);

        mnuVete.setText("Módulo de Veterinarios");
        mnuVete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVeteActionPerformed(evt);
            }
        });
        jMenu2.add(mnuVete);

        mnuClint.setText("Módulo de clientes");
        mnuClint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClintActionPerformed(evt);
            }
        });
        jMenu2.add(mnuClint);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel3)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdminActionPerformed
        vistaadministrador frm = new vistaadministrador();
        frm.setVisible(true);
        this.setVisible(false);
        
        Veterinario vet1 = new Veterinario();
        DireccionVeterinario vet2 = new DireccionVeterinario();
        ConsultaVeterinario modC = new ConsultaVeterinario();
        tablaVeterinario frm28 = new tablaVeterinario();
        
        Categoria cat = new Categoria();
        ConsultaCategoria modS = new ConsultaCategoria();
        tablaCategoria frm2811 = new tablaCategoria();
        
        
        
        Cita cit = new Cita();
        ConsultaCita modH = new ConsultaCita();
        tablaCita frm333 = new tablaCita();
        
        CtrlVeterinario ctrl;
        ctrl = new CtrlVeterinario (vet1, vet2, modC, frm, frm28);
        ctrl.iniciar();
        
        CtrlCita ctrl44;
        ctrl44 = new CtrlCita( cit,  modH,  frm,  frm333);
        ctrl44.iniciar();
        
        CtrlCategoria ctrl5656;
        ctrl5656 = new CtrlCategoria( cat,  modS,  frm);
        ctrl5656.iniciar();
        
        
    }//GEN-LAST:event_mnuAdminActionPerformed

    private void mnuVeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVeteActionPerformed
        vistaVeterinario frm5 = new vistaVeterinario();
        frm5.setVisible(true);
        this.setVisible(false);
        
        Servicio ser1 = new Servicio();
        ConsultaServicio modW = new ConsultaServicio();
        
        Paciente paa = new Paciente();
        HistoricoPaciente hisPa = new HistoricoPaciente();
        ConsultaPaciente modZ = new ConsultaPaciente();
        
        Cliente clie = new Cliente();
        ConsultaCliente modJ = new ConsultaCliente();
        
        Cita cit = new Cita();
        ConsultaCita modH = new ConsultaCita();
        tablaCita frm333 = new tablaCita(); 
        
        
        Categoria cat1 = new Categoria();
        ConsultaCategoria consuCat = new ConsultaCategoria();
        

        CtrlServicio ctrl;
        ctrl = new CtrlServicio (ser1, modW, frm5);
        ctrl.iniciar();
        
        CtrlPaciente ctrl2;
        ctrl2 = new CtrlPaciente(paa, modZ, frm5);
        ctrl2.iniciar();
        
        CtrlCita2 ctrl34;
        ctrl34 = new CtrlCita2( cit,  modH,  frm5,  frm333);
        ctrl34.iniciar();
        
        CtrlCliente ctrl45;
        ctrl45 = new CtrlCliente(clie,  modJ,  frm5);
        ctrl45.iniciar();
        
        
              
        
        
    }//GEN-LAST:event_mnuVeteActionPerformed

    private void mnuClintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClintActionPerformed
        // TODO add your handling code here:
        vistaCliente vista777 = new vistaCliente();
        vista777.setVisible(true);
        this.setVisible(false);
        
        Cliente clie2 = new Cliente();
        ConsultaCliente modJ = new ConsultaCliente();
        
        
        CtrlCliente2 ctr13;
        ctr13 = new CtrlCliente2(clie2,  modJ,  vista777);
        ctr13.iniciar();
        
        
        
       
    }//GEN-LAST:event_mnuClintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuGestiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuGestiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuGestiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuGestiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuGestiones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private javax.swing.JMenuItem mnuAdmin;
    private javax.swing.JMenuItem mnuClint;
    private javax.swing.JMenuItem mnuVete;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
