/*
 * Bases Datos
 * Proyecto I
 * Tec
 * 2020
 */
package Vista;
/**
 *
 * @author danBoga
 */
import Controlador.CtrlVeterinario;
import Modulo.ConsultaVeterinario;
import Modulo.DireccionVeterinario;
import Modulo.Veterinario;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author julian
 */
public class tablaVeterinario extends javax.swing.JFrame {

    /**
     * Creates new form tablaVeterinario
     */
    public tablaVeterinario() {
        initComponents();
        
        try{
            DefaultTableModel modelo = new DefaultTableModel();
            DefaultTableModel modelo2 = new DefaultTableModel();
            jtVeterinario.setModel(modelo);
            jtableDireccionVete.setModel(modelo2);
            
            PreparedStatement ps = null;
            PreparedStatement ps2= null;
            ResultSet rs = null;
            ResultSet rs2 = null;
            Conexion conn = new Conexion();
            Connection con = conn.getConexion();
            String sql = "SELECT nombre, fecha, horarioAtencion, ubicacionMaps FROM VETERINARIO";
            String sql2 = "SELECT id_vet, provincia, canton, distrito, señas, telefono, correo, web FROM DIRECCION_VETERINARIO ";
            ps2 = con.prepareCall(sql2);
            ps = con.prepareStatement(sql);
            rs2 = ps2.executeQuery();
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            ResultSetMetaData rsMd2 = rs.getMetaData();
            int cantidadColumnas2 = rsMd2.getColumnCount();
            int cantidadColumnas = rsMd.getColumnCount();
            
            modelo.addColumn("id");
            modelo.addColumn("nombre");
            modelo.addColumn("fecha");
            modelo.addColumn("horarioAtencion");
            modelo.addColumn("ubicacionMaps");
            
            modelo2.addColumn("id_vet");
            modelo2.addColumn("provincia");
            modelo2.addColumn("canton");
            modelo2.addColumn("distrito");
            modelo2.addColumn("señas");
            modelo2.addColumn("telefono");
            modelo2.addColumn("correo");
            modelo2.addColumn("web");
            
            
            
            
            while(rs.next() && rs2.next()){
                Object[] filas = new Object[cantidadColumnas];
                Object[] filas2 = new Object[cantidadColumnas2];
                for(int i = 0; i< cantidadColumnas; i++){
                    filas[i] = rs.getObject(i +1);
                    filas2[i] = rs2.getObject(i +1);
                }
                modelo.addRow(filas);
                modelo2.addRow(filas2);
            }
            
            
            
        }catch(SQLException ex){
            System.err.println(ex.toString());
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtVeterinario = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtableDireccionVete = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuregresar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtVeterinario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "nombre", "fecha", "horarioAtencion", "ubicacionMaps"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtVeterinario);

        jtableDireccionVete.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id_vet", "provincia", "canton", "distrito", "señas", "telefono", "correo", "web"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtableDireccionVete);

        jLabel1.setText("Veterinarios");

        jLabel2.setText("Dirección Veterinarios");

        jLabel3.setText("Id");

        jButton1.setText("Consultar");

        jButton2.setText("Regresar");

        jMenu1.setText(":$");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        menuregresar.setText("Regresar");
        menuregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuregresarActionPerformed(evt);
            }
        });
        jMenu2.add(menuregresar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane2))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(27, 27, 27))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuregresarActionPerformed
        // TODO add your handling code here:
        vistaadministrador frm = new vistaadministrador();
        frm.setVisible(true);
        this.setVisible(false);
        
        Veterinario vet1 = new Veterinario();
        DireccionVeterinario vet2 = new DireccionVeterinario();
        ConsultaVeterinario modC = new ConsultaVeterinario();
        tablaVeterinario frm28 = new tablaVeterinario();
        tablaServicio frm2811 = new tablaServicio();
        
        CtrlVeterinario ctrl;
        ctrl = new CtrlVeterinario (vet1, vet2, modC, frm, frm28);
        ctrl.iniciar();
    }//GEN-LAST:event_menuregresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tablaVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tablaVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tablaVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tablaVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tablaVeterinario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable jtVeterinario;
    private javax.swing.JTable jtableDireccionVete;
    private javax.swing.JMenuItem menuregresar;
    // End of variables declaration//GEN-END:variables
}
